version: "2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: start
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=tenfour
      - DB_USERNAME=tenfour
      - DB_PASSWORD=tenfour
      - APP_ENV=testing
      - APP_API_DOMAIN=localhost
      - REDIS_HOST=redis
      - DOCKERIZE_WAIT_FOR_mysql=tcp://mysql:3306
      - DOCKERIZE_WAIT_FOR_redis=tcp://redis:6379
    extra_hosts:  # TODO: how things break if we take these out?
      - "tenfour.dev:127.0.0.1"
      - "api.tenfour.dev:127.0.0.1"
      - "tenfour.local:127.0.0.1"
      - "api.tenfour.local:127.0.0.1"
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=tenfour
      - MYSQL_USER=tenfour
      - MYSQL_PASSWORD=tenfour
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  redis:
    image: redis:3.2
    environment:
      - REDIS_HOST=redis
